[tool.poetry]
name = "coursework-5-sql"
version = "0.1.0"
description = ""
authors = ["Konovalova Ekaterina <konovalova_ekaterina_a@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
